[package]
name = "bcsp-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
bcsp-contracts = { version = "=0.0.0", path = "../bcsp-contracts" }
bcsp-domain = { version = "=0.0.0", path = "../bcsp-domain" }
serde.workspace = true
thiserror.workspace = true
time.workspace = true

[dev-dependencies]
proptest.workspace = true
