[package]
name = "bcsp-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "bcsp-server"
path = "src/main.rs"

[dependencies]
bcsp-public-runtime = { version = "=0.0.0", path = "../../crates/bcsp-public-runtime" }
tokio.workspace = true
tracing.workspace = true
